<?php

namespace hnr\sircimBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * EstudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudioRepository extends EntityRepository
{
	public function seleccionarEstudios()
    {
    	
         return $this->getEntityManager()
            ->createQuery('SELECT e 
                           FROM minsalacademicaAnBundle:Evaluacion e
                           WHERE e.porcentaje > 0.5
                           ORDER BY e.id ASC')
                ->getResult();
    }
}
