<?php

namespace hnr\sircimBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	public function seleccionarEmpleados()
    {
    	$conn = $this->get('doctrine.dbal.siap_connection');           
        $empleados = $conn->fetchAll("
        		SELECT idempleado
                FROM 
                	vw_empleado_info");
        return $empleados;
        // return $this->getEntityManager()
        //     ->createQuery('SELECT e 
        //                    FROM minsalacademicaAnBundle:Evaluacion e
        //                    WHERE e.porcentaje >= 0.5
        //                    ORDER BY e.id ASC')
        //         ->getResult();
    }
}
